TrajectoryPlannerROS:
  max_vel_x: 0.07
  min_vel_x: 0.05
  max_vel_theta: 0.07
  min_in_place_vel_theta: 0.05

  acc_lim_theta: 4.0
  acc_lim_x: 3.7
  acc_lim_y: 3.5

  holonomic_robot: true
  y_vels: [-0.1, -0.05, 0.05, 0.1]
  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.2
