footprint: [[0.290,0.190], [0.290,-0.190], [-0.290,-0.190], [-0.290,0.190]]
transform_tolerance: 1.5
obstacle_range: 2.5

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: base_laser_front_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}